name: new-businessflow
description: Define y configura un nuevo flujo de negocio (levanta infra, repos, etc)

on:
  workflow_dispatch:
    inputs:
      name:
        required: true
        description: Nombre del flujo de negocio
      description:
        description: Descripción del flujo
      instance_type: 
        required: true
        description: Tipo de instancia cloud (nodos)
      cidr:
        required: true
        description: Rango de conexiones de red
      min_size: 
        description: Tamaño mínimo de nodos
      max_size:
        description: Tamaño máximo de nodos
      desired_size: 
        description: Tamaño deseado

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Create .env file
        working-directory: platform-engineering/CLI
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        run: |
          echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" > .env
          echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> .env
          echo "GITHUB_TOKEN=$GITHUB_TOKEN" >> .env
      
      - name: Install and init Devbox
        uses: jetpack-io/devbox-install-action@v0.13.0
        with:
          enable-cache: 'true'
          refresh-cli:  'true'
          devbox-version: 0.15.0
          project-path: 'platform-engineering/CLI'
      
      - name: Define new businessflow
        working-directory: platform-engineering/CLI
        run: |
          devbox run bancli businessflow new \
            --name="${{ github.event.inputs.name }}" \
            --description="${{ github.event.inputs.description }}" \
            --instance-type="${{ github.event.inputs.instance_type }}" \
            --cidr="${{ github.event.inputs.cidr }}" \
            --min-size="${{ github.event.inputs.min_size }}" \
            --max-size="${{ github.event.inputs.max_size }}" \
            --desired-size="${{ github.event.inputs.desired_size }}"